name: tinkoff_acquiring
description: Flutter Tinkoff Acquiring SDK is a simple way to integrate payments into your mobile application.
version: 1.0.2
repository: https://github.com/MadBrains/Tinkoff-Acquiring-SDK-Flutter
issue_tracker: https://github.com/MadBrains/Tinkoff-Acquiring-SDK-Flutter/issues
homepage: https://madbrains.ru/

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  meta: ^1.2.3
  collection: ^1.14.13
  http: ^0.12.2
  crypto: ^2.1.5
  crypton: ^1.1.3
  webview_flutter: ^1.0.5
  json_annotation: ^3.1.0

dev_dependencies:
  build_runner: ^1.10.4
  json_serializable: ^3.5.0

  flutter_test:
    sdk: flutter