name: pull_request

on:
  pull_request:
    branches:
      - main

jobs:   
  format:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: 'Git Checkout'
        uses: actions/checkout@v3
      - name: 'Install Flutter'
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: 'Install Tools'
        run: flutter pub global activate fvm; make init;
      - name: 'Format Code'
        run: make fix
      - name: 'Validate Formatting'
        run: ./tool/validate-formatting.sh